name = "finchtech-my-frontend"
main = ".open-next/worker.js"
compatibility_date = "2026-08-20"
compatibility_flags = ["nodejs_compat"]
account_id = "28970b96b4880e4f41cc0487104898a0"
workers_dev = true

[vars]
ENVIRONMENT = "production"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
